
# This file contains the implementation of a multinomial logistic regression 
# model trained on a synthetic dataset with overlapping classes. The code is 
# structured into four main sections: data generation, model math, training loop, 
# and visualization of decision boundaries.

# The code is generated by GPT-4 and is intended for educational purposes to 
# demonstrate the implementation of logistic regression from scratch.
# The dataset consists of 5 classes with 50 points each, generated from 
# normal distributions with increased variance to create overlap between classes. 
# The model is trained using gradient descent, and the decision boundaries are 
# visualized using a contour plot.

# The code is programmed in procedural programming style, without the use of classes 
# or object-oriented programming concepts. The students are expected to implement 
# a library that minics the functionality of scikit-learn's logistic regression in 
# Object-oriented style, programming paradigm and logistic regression model with 
# regularization term.

# The students are encouraged to use Gemini or ChatGPT to help them understand the code 
# and implement the required functionality in C++ to acquire any necessary knowledge about 
# the mathematical formulation of the logistic regression model, the gradient descent 
# method, and the regularization term. However, the students are expected to write the code 
# themselves without copying and pasting from any source, including the provided 
# Python code. The students should understand the code and implement it in C++ using 
# their own words and style.

# Author: Gemini

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.utils import shuffle

# --- 1. DATA GENERATION (With Overlap) ---
def generate_overlapping_data(n_per_class=50):
    """Generates 5 classes with 50 points each. Increased variance creates overlap."""
    data = []
    centers = [(2, 2), (2, 7), (5, 4.5), (8, 2), (8, 7)]
    
    for class_id, (cx, cy) in enumerate(centers):
        for _ in range(n_per_class):
            # Increased scale (1.2) ensures points cross into other class territories
            x1 = np.random.normal(cx, 1.2)
            x2 = np.random.normal(cy, 1.2)
            data.append([x1, x2, class_id])
            
    df = pd.DataFrame(data, columns=['feat1', 'feat2', 'label'])
    # Shuffle so the model doesn't see classes in perfect blocks during training
    return shuffle(df, random_state=42).reset_index(drop=True)

# --- 2. MODEL MATH ---
def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

def forward_prop(X, W, b):
    z = np.dot(X, W) + b
    return softmax(z)

# --- 3. TRAINING LOOP ---
def train_model(X, y, lr=0.05, epochs=2000):
    num_samples, num_features = X.shape
    num_classes = len(np.unique(y))
    
    # Initialization
    W = np.random.randn(num_features, num_classes) * 0.01
    b = np.zeros((1, num_classes))
    y_oh = pd.get_dummies(y).values
    
    print(f"Training on {num_samples} points...")
    for epoch in range(epochs):
        # Forward
        probs = forward_prop(X, W, b)
        
        # Gradient
        error = probs - y_oh
        dW = (1 / num_samples) * np.dot(X.T, error)
        db = (1 / num_samples) * np.sum(error, axis=0, keepdims=True)
        
        # Update
        W -= lr * dW
        b -= lr * db
        
        if epoch % 500 == 0:
            loss = -np.mean(np.sum(y_oh * np.log(probs + 1e-9), axis=1))
            print(f"Epoch {epoch}: Loss {loss:.4f}")
            
    return W, b

# --- 4. VISUALIZATION (Decision Boundaries) ---
def plot_boundaries(X, y, W, b, filename):
    plt.figure(figsize=(10, 8))
    
    # Create a grid of points covering the feature space
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.05),
                         np.arange(y_min, y_max, 0.05))
    
    # Predict for every point in the grid
    grid_points = np.c_[xx.ravel(), yy.ravel()]
    probs = forward_prop(grid_points, W, b)
    predictions = np.argmax(probs, axis=1)
    predictions = predictions.reshape(xx.shape)
    
    # Plot background colors
    plt.contourf(xx, yy, predictions, alpha=0.3, cmap='viridis')
    
    # Plot the original data points
    scatter = plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis', edgecolors='k', s=40)
    
    plt.title("Multinomial Logistic Regression: Decision Boundaries (Non-Separable)")
    plt.xlabel("Feature 1")
    plt.ylabel("Feature 2")
    plt.savefig(filename)
    plt.close()
    print(f"Boundary plot saved to {filename}")

# --- EXECUTION ---
Path("./data").mkdir(exist_ok=True)

df = generate_overlapping_data(50)
X_train = df[['feat1', 'feat2']].values
y_train = df['label'].values

# Run Training
W_final, b_final = train_model(X_train, y_train)

# Generate Visual
plot_boundaries(X_train, y_train, W_final, b_final, "./data/decision_boundaries.png")